name: "build-images"
on:
  workflow_dispatch:
    inputs:
      owner:
        type: string
        default: darkflib
      image:
        required: true
        type: string
      push:
        default: true
        type: boolean

  workflow_call:
    inputs:
      owner:
        type: string
        default: darkflib
      image:
        required: true
        type: string
      push:
        default: true
        type: boolean

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: darkflib
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Login to github container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v1
    - run: |
        echo ::group::build image ${{ inputs.image }}:latest
          docker build -t ${{ inputs.image }} ${{ inputs.image }}
        echo ::endgroup::
        if [ -e "${{ inputs.image }}/tags.yaml" ]; then
          for tag in $(cat "${{ inputs.image }}/tags.yaml" | docker run --rm -i whalebrew/yq  -r '.versions[]'); do
            echo ::group::build image ${{ inputs.image }}:${tag}
              docker build -t ${{ inputs.image }}:${tag} --build-arg VERSION=${tag} ${{ inputs.image }}
            echo ::endgroup::
          done
        fi
    - if: inputs.push
      run: |
        docker tag ${{ inputs.image }} ${{ inputs.owner}}/${{ inputs.image }}
        docker tag ${{ inputs.image }} ghcr.io/${{ inputs.owner }}/${{ github.event.repository.name }}/${{ inputs.image }}
        if [ -e "${{ inputs.image }}/tags.yaml" ]; then
          for tag in $(cat "${{ inputs.image }}/tags.yaml" | docker run --rm -i whalebrew/yq  -r '.versions[]'); do
            docker tag ${{ inputs.image }}:${tag} ${{ inputs.owner}}/${{ inputs.image }}:${tag}
            docker tag ${{ inputs.image }}:${tag} ghcr.io/${{ inputs.owner }}/${{ github.event.repository.name }}/${{ inputs.image }}:${tag}
            docker push ${{ inputs.owner}}/${{ inputs.image }}:${tag}
            docker push ghcr.io/${{ inputs.owner}}/${{ github.event.repository.name }}/${{ inputs.image }}:${tag}
          done
        fi
